name: build-test.yml
on:
  pull_request:
    branches:
      - develop
      - staging/*
jobs:
    build-test:
      name: Build and Test
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - name: Check out the repo
          uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - name: Install dependencies
          run: bun install
        - name: Build
          run: bun run build
